#!/usr/bin/env sh

printenv > /tmp/.envfile

docker run --rm -ti \
  --volume /tmp:/tmp \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume $PWD:$PWD \
  --workdir $PWD \
  --env-file /tmp/.envfile \
  getpopper/popper:v2.7.0 $@
